# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/faces"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/jte"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/qute"
    schedule:
      interval: "daily"
  - package-ecosystem: "maven"
    directory: "/vaadin"
    schedule:
      interval: "daily"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
